### ISSUE TITLE
Nothing more than syntax coloring

### ISSUE THREAD

**Issue by yves-dolce** [gorkem/vscode-java#15]
After installing this extension, I installed OpenJDK 1.8.0_102-1.redhat and set the JAVA_HOME environment variable. Java files load successfully and I have syntax coloring but nothing else! (e.g. code lens, code completion, ...).
Then, tried with 0.0.2 but no luck so I followed the troubleshooting section without any more luck.
Am I the only one to have this issue?
Windows 10 x64 Anniversary Edition.

**Comment by gorkem** [comment]
Can you confirm that the plugins folder under _~/.vscode/extensions/redhat.java-0.0.2/server_ exists? 
Do you see the thumbs up on the lower bottom right?
If you are seeing the thumbs up that means the extension is working but probably is not recognizing your project. Does your project have a maven pom.xml ? Current version only recognizes projects with a pom.xml so that it can resolve dependencies. 

Can you share the project that you are trying to open.

**Comment by yves-dolce** [comment]
I indeed do **not** have such pom.xml file: my "project" was just a folder with one .java file.
Thanks for clarifying this!

**Comment by gorkem** [comment]
We are not supporting that project structure yet.
